INSERT INTO citys VALUES(1,'Aracajú',26);
INSERT INTO citys VALUES(2,'Belém',14);
INSERT INTO citys VALUES(3,'Belo Horizonte',13);
INSERT INTO citys VALUES(4,'Boa Vista',23);
INSERT INTO citys VALUES(5,'Brasília',7);
INSERT INTO citys VALUES(6,'Campo Grande',12);
INSERT INTO citys VALUES(7,'Cuiabá',11);
INSERT INTO citys VALUES(8,'Curitiba',16);
INSERT INTO citys VALUES(9,'Florianópolis',24);
INSERT INTO citys VALUES(10,'Fortaleza',6);
INSERT INTO citys VALUES(11,'Goiânia',9);
INSERT INTO citys VALUES(12,'João Pessoa',15);
INSERT INTO citys VALUES(13,'Macap ',3);
INSERT INTO citys VALUES(14,'Maceió',2);
INSERT INTO citys VALUES(15,'Manaus',4);
INSERT INTO citys VALUES(16,'Natal',20);
INSERT INTO citys VALUES(17,'Palmas',27);
INSERT INTO citys VALUES(18,'Porto Alegre',21);
INSERT INTO citys VALUES(19,'Porto Velho',22);
INSERT INTO citys VALUES(20,'Recife',17);
INSERT INTO citys VALUES(21,'Rio Branco',1);
INSERT INTO citys VALUES(22,'Rio de Janeiro',19);
INSERT INTO citys VALUES(23,'Salvador',5);
INSERT INTO citys VALUES(24,'São Luis',10);
INSERT INTO citys VALUES(25,'São Paulo',25);
INSERT INTO citys VALUES(26,'Teresina',18);
INSERT INTO citys VALUES(27,'Vitória',8);