INSERT INTO states VALUES(1,'AC','Acre');
INSERT INTO states VALUES(2,'AL','Alagoas');
INSERT INTO states VALUES(3,'AP','Amapá');
INSERT INTO states VALUES(4,'AM','Amazonas');
INSERT INTO states VALUES(5,'BA','Bahia');
INSERT INTO states VALUES(6,'CE','Ceará');
INSERT INTO states VALUES(7,'DF','Distrito Federal');
INSERT INTO states VALUES(8,'ES','Espírito Santo');
INSERT INTO states VALUES(9,'GO','Goiás');
INSERT INTO states VALUES(10,'MA','Maranhão');
INSERT INTO states VALUES(11,'MT','Mato Grosso');
INSERT INTO states VALUES(12,'MS','Mato Grosso do Sul');
INSERT INTO states VALUES(13,'MG','Minas Gerais');
INSERT INTO states VALUES(14,'PA','Pará');
INSERT INTO states VALUES(15,'PB','Paraíba');
INSERT INTO states VALUES(16,'PR','Paraná');
INSERT INTO states VALUES(17,'PE','Pernambuco');
INSERT INTO states VALUES(18,'PI','Piauí');
INSERT INTO states VALUES(19,'RJ','Rio de Janeiro');
INSERT INTO states VALUES(20,'RN','Rio Grande do Norte');
INSERT INTO states VALUES(21,'RS','Rio Grande do Sul');
INSERT INTO states VALUES(22,'RO','Rondônia');
INSERT INTO states VALUES(23,'RR','Roraima');
INSERT INTO states VALUES(24,'SC','Santa Catarina');
INSERT INTO states VALUES(25,'SP','São Paulo');
INSERT INTO states VALUES(26,'SE','Sergipe');
INSERT INTO states VALUES(27,'TO','Tocantins');
